[bug]: Use English as default (non-supported) language
ideafast/ideafast-patientapp pull request #58
Opened 2020-10-07 12:23 UTC by b9019367

Resolves: #issue-number-here

- [x ] Assigned a Reviewer to the **PR**.
- [ ] Assigned a Project to the **PR**.
- [ ] Added **tests** for changed code.

## What Changed and Why?

  1. In the previous PR we introduced multilingual (i18n) support. However, when a user has a language on their phone set to a non-supported language (e.g. French), then the settings page breaks due to current logic. This PR resolves this bug.

## To Reproduce
  1. Set the phone's language to a not supported language (e.g. French) and navigate to Settings. Note there is an error!

## To Test
   1. Set the phone's language to a support language, e.g. English, navigate around the app and change the language from English to something else (German);
   2. Set the phone's language to one that is not supported (French) and navigate to settings.
       1. Note that there is not only no error, but that English is used as the default language.

2020-10-08 08:43 UTC, jawrainey requested changes

2020-10-08 08:43 UTC, jawrainey commented on src/ducks/initialState.js
> +};
Great work finding this bug @b9019367! This code resolves both the bug and surpresses the error produced by the tests. The error is produced because `i18n.languages` is `undefined` and so `.includes` does not exist. 

The try/catch might accidently catch other (non TypeError) issues that would make it tricky to debug in the future. As a suggestion, one alternative approach would be to check if `i18n.languages` exists before calling `.includes`, e.g.

```javascript
const userLang = i18n.languages && i18n.languages.includes(i18n.language) ? i18n.language : 'en';
```

This conditional be simplified using [optional changing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) as:

```javascript
const userLang = i18n.languages?.includes(i18n.language) ? i18n.language : 'en';
```

This way `userLang` could also become a variable.

2020-10-08 12:14 UTC, drewmiley commented on src/ducks/initialState.js
> +// Added a function since ./__test__/ducks/reducer-test.js failed to run i18n.languages.INCLUDES
Is this comment still relevant?

2020-10-08 12:14 UTC, drewmiley commented on src/ducks/initialState.js
> +  userLang: userLang,
Could just put the one line statement in here?

2020-10-08 12:55 UTC, b9019367 commented on src/ducks/initialState.js
> +  userLang: userLang,
Jay adviced to make a new variable since it is easier to read.

2020-10-08 13:25 UTC, drewmiley commented on src/ducks/initialState.js
> +  userLang: userLang,
Ok. You can use this: https://alligator.io/js/object-property-shorthand-es6/

2020-10-10 13:49 UTC, jawrainey commented on src/ducks/initialState.js
> +let userLang = i18n.languages?.includes(i18n.language) ? i18n.language : 'en';
This declaration should be `const` not `let` since the variable won't change in this definition (although it will via reducers), but otherwise all looks great! Great idea to change DEVICE->devices

2020-10-10 14:46 UTC, jawrainey commented
Tested locally by changing language to French. Default language was English, no error when going to Settings. Also tested in German (supported language) and works as expected. Code LGTM. Good job

2020-10-10 14:47 UTC, merged